# Generated by Django 5.1 on 2024-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_email_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cls',
            field=models.CharField(blank=True, choices=[('A1', '1.A'), ('A2', '2.A'), ('A3', '3.A'), ('A4', '4.A'), ('A5', '5.A'), ('A6', '6.A'), ('B1', '1.B'), ('B2', '2.B'), ('B3', '3.B'), ('B4', '4.B'), ('B5', '5.B'), ('B6', '6.B'), ('C1', '1.C'), ('C2', '2.C'), ('C3', '3.C'), ('C4', '4.C')], max_length=2),
        ),
    ]
