# Generated by Django 5.1 on 2024-08-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_error'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Error',
        ),
    ]
